### ISSUE TITLE
Frontend: Tweaks

### ISSUE THREAD

**Issue by chrishappy** [chrishappy/smooth-shopping#20]
- [x] Show product descriptions when clicking on a product
- [x] Show a message bar if added too many of a product
- [x] Show snackbar if usernams/password is incorrect

**Comment by alisonrwu** [comment]
For message bar if too many of a product (are added to cart?) I added a snackbar for general notifications.
See 68fa645be30d14c033331b1ee6fdd6ce77a2d2d4

**Comment by alisonrwu** [comment]
Oops ignore that first reference (decided to just push to master lol).

I think just need to use the snackbar now, which is just updating the reactive variables defined in the component as needed.

Feel free to add more tweaks as necessary I guess too.

**Comment by alisonrwu** [comment]
ef1c896 finishes 3rd tick box

**Comment by chrishappy** [comment]
2nd Tick: resolved alternatively by disabling the add/minus buttons when quantities are exceeded.
